### PR TITLE
Add login with github button

### PR DESCRIPTION
**Pull request by sdankel**
Adds authorization with [Github on behalf of a user](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-a-github-app-on-behalf-of-a-user).

Apr-02-2024 21-41-36

### Login (first time)
1. When the user clicks login, the frontend redirects the user to install the github app
2. When they finish authorizing, github redirects back to the website, with a `code` as a query parameter
3. The frontend stores this code temporarily in localstorage, so that it's available to the original window
4. The frontend calls the server's `login` API with this code, and removes it from localstorage
5. The server calls github's `access_token` API to exchange the code for a user access token
6. The server then uses the token to request the user's information, stores the token in a session store, and responds to the client. Currently the session store is just using the server state. In a future PR, this will be moved to a session database table.
7. The client stores the session ID in localstorage.

### Login (returning)
1. When the user clicks login, the frontend redirects the user to install the github app
2. The same redirection flow occurs, and the immediately closes without user input.
3. The same login flow occurs, with a new session ID. 

### Already logged in
1. The frontend checks if there is a session ID in localstorage. If so, it calls the server's `session` API
2. The server looks up the session and returns the User, if one is found.

### Logout
1. The frontend clears the session ID from localstorage and sets the `githubUser` react state to null

This is still early in development. Future PRs will include:
1. Storing sessions in a SQL database table
2. Expiring sessions appropriately
4. Returning more information about the user
5. Potential improvements on the frontend to call the session API less often.
6. Tests! I will spend time writing tests once the implementation is more fleshed out.

I also started building out the search bar and the react routing for different pages.

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
Nice work, great to see this coming along. 

I just pulled down and tried to run locally. The first time I clicked login with github, the pop-up window opened and I clicked Authorize. The pop-up window went away but did not seem to log my in. Each subsequent time I click on the window it does what is shown in the video below. Just wondering if I'm doing something wrong?


https://github.com/FuelLabs/forc.pub/assets/1289413/c53952cc-71de-468c-b03e-28c326c9c979

**Comment by JoshuaBatty** [comment]
Just tested again with 3 browsers

Brave: doens't work -> same as video above
Chrome: works
Safari: works

**Comment by sdankel** [comment]
> Just tested again with 3 browsers
> 
> Brave: doens't work -> same as video above Chrome: works Safari: works

Good catch! The problem has to do with the login  request - the server never receives it.

If I change `0.0.0.0`  to `localhost`, it works in Brave. Maybe it’s some extra security setting in brave. I think this would only be an issue testing locally.

image

**Review by JoshuaBatty — APPROVED** [review]
🙌

**Pull request merged**
